# Generated by Django 5.1.1 on 2024-09-11 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'get_latest_by': 'created_at'},
        ),
    ]
